[package]
name = "vrb-profiles"
version = "0.1.0"
edition = "2021"
description = "Library for working with the 'profile' entity (user)."
rust-version = "1.87.0"
keywords = ["profiles", "vrb-profiles"]
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
diesel = { version = "2.2.10", features = ["postgres", "r2d2", "chrono"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel_migrations = "2.2.0"
r2d2 = "0.8.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
utoipa = { version = "5.3.1", features = ["chrono", "actix_extras"] }
vrb-dbase = { version = "0.1", path="../vrb_dbase" }
vrb-tools = { version = "0.1", path="../vrb_tools" }

[profile.dev]
debug = 1
