[package]
name = "vrb-streams"
version = "0.1.0"
edition = "2021"
description = "The library stores modules for working with streams."
rust-version = "1.87.0"
keywords = ["vrb-streams"]
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]

[profile.dev]
debug = 1
